### ISSUE TITLE
Atom build should support flags for install and package creation

### ISSUE THREAD

**Issue by curiousercreative** [hypersad/atom#5]
Build flags `--install` and `--create-debian-package` do not currently work. Full list of flags that linux build on other architectures: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#scriptbuild-options

**Comment by hypersad** [comment]
Can you told me what error you got when trying to use this flags?

**Comment by curiousercreative** [comment]
@hypersad I don't remember. Let me try them now.

**Comment by curiousercreative** [comment]
Build with Install flag fails. Output:
```
maru@jessie:~/Desktop/atom$ node script/build --install
Node:	v6.10.2
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/maru/Desktop/atom/node_modules/.dependencies-fingerprint 1378bc15a3a7190fe2ea8d12d9ba9dc81033cd7e
Cleaning /home/maru/Desktop/atom/out
Copying assets to /home/maru/Desktop/atom/out/app
Transpiling Babel paths in /home/maru/Desktop/atom/out/app
Transpiling CoffeeScript paths in /home/maru/Desktop/atom/out/app
Transpiling CSON paths in /home/maru/Desktop/atom/out/app
Transpiling PEG.js paths in /home/maru/Desktop/atom/out/app
Generating module cache for /home/maru/Desktop/atom/out/app
Generating pre-built less cache in /home/maru/Desktop/atom/out/app/less-compile-cache
Generating metadata for /home/maru/Desktop/atom/out/app/package.json
Generating API docs at /home/maru/Desktop/atom/docs/output/atom-api.json
Dumping symbols in /home/maru/Desktop/atom/out/symbols
Running electron-packager on /home/maru/Desktop/atom/out/app with app name "atom"
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
WARNING: The app-copyright parameter is deprecated when used from JS, use appCopyright instead. It will be removed in the next major version.
WARNING: The app-version parameter is deprecated when used from JS, use appVersion instead. It will be removed in the next major version.
WARNING: The build-version parameter is deprecated when used from JS, use buildVersion instead. It will be removed in the next major version.
WARNING: The app-bundle-id parameter is deprecated when used from JS, use appBundleId instead. It will be removed in the next major version.
WARNING: The extend-info parameter is deprecated when used from JS, use extendInfo instead. It will be removed in the next major version.
WARNING: The helper-bundle-id parameter is deprecated when used from JS, use helperBundleId instead. It will be removed in the next major version.
Packaging app for platform linux armv7l using electron v1.4.16
Changing permissions for node files in /home/maru/Desktop/atom/out/atom-1.15.0-armv7l
Copying non-ASAR resources to /home/maru/Desktop/atom/out/atom-1.15.0-armv7l/resources
Writing LICENSE.md to /home/maru/Desktop/atom/out/atom-1.15.0-armv7l/resources
Application bundle created at /home/maru/Desktop/atom/out/atom-1.15.0-armv7l
Skipping creating debian package. Specify the --create-debian-package option to create it.
Skipping creating rpm package. Specify the --create-rpm-package option to create it.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Removing previously installed "atom-1.15.0-armv7l" at "/usr/local/share/atom"
Installing "atom-1.15.0-armv7l" at "/usr/local/share/atom"
Error: EACCES: permission denied, unlink '/usr/local/share/atom/LICENSE'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1103:18)
    at copyFileSync (/home/maru/Desktop/atom/script/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:13:10)
    at copySync (/home/maru/Desktop/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:7)
    at /home/maru/Desktop/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at Object.copySync (/home/maru/Desktop/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at module.exports (/home/maru/Desktop/atom/script/lib/install-application.js:59:8)
    at dumpSymbols.then.then.then.packagedAppPath (/home/maru/Desktop/atom/script/build:101:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Build with package creation succeeds, however error when attempting to install package:
>Error: Wrong architecture 'arm'

I had a hack to get around this previously, the architecture it's looking for is `armhf` I believe.

**Comment by curiousercreative** [comment]
@hypersad I submitted a pull request for a fix that allows me to install the generated debian package. I'd love for other users to verify that it works for them.

https://github.com/hypersad/atom/pull/7

**Comment by hypersad** [comment]
Merged. Can someone else test it too?

**Comment by djarami** [comment]
This might be dumb to mention, but I don't think this is going to work the same on the raspberry pi. 
https://www.raspberrypi.org/blog/raspbian-jessie-is-here/ and probably has a separate install method and package manager too.  I know that I don't know much at all here and also that what's there I don't think will work.   Maybe worth opening a separate issue for this.

**Comment by curiousercreative** [comment]
@djarami why don't you think it'll work? You're referring to the pull request targeting `armhf` architecture, correct? Probably worth giving it a shot to see what happens. If you pull from this repo, you shouldn't have to run `node script/clean` before `node script/build --create-debian-package` and that package creation is quick relative to the full build from scratch.

**Comment by djarami** [comment]
Can you guys tell me what models of chromebook are ARM7l - seems like the different models have different CPU's aka - Celeron.  Only one I think has the ARM7l is the Samsung one - but that one seems to be more costly.  I'm looking for something low cost.

**Comment by djarami** [comment]
@curiousercreative I've only been doing the `node script/build` and also the `--install` option which is where I got a bunch of errors.  Never tried the `--create-debian-package`  I will give it a try.

**Comment by curiousercreative** [comment]
@djarami I'm not familiar with Chromebooks unfortunately. I'm running Jessie from my Nexus 5 Android phone within a LXC (a lightweight virtualization) via a ROM called [MaruOS](http://maruos.com/).

**Comment by hypersad** [comment]
@curiousercreative I'm running Xubuntu 14.04 on Android tablet with dock-station with dualboot :^)

**Comment by curiousercreative** [comment]
@hypersad out of curiosity, what Android tablet and what software is enabling you to dual boot and run linux natively?

**Comment by hypersad** [comment]
@curiousercreative ASUS Transformer Pad TF300TG. I'm using Kexec (Kexec is a system call that enables you to load and boot into another kernel from the currently running kernel).

**Comment by hypersad** [comment]
Fixed --compress-artifacts (archive was named with arm architecture)

**Comment by hypersad** [comment]
Yesterday night fixed --create-debian-package. Try to upload fix today.

**Comment by curiousercreative** [comment]
@hypersad, my pull request that you merged yesterday should have fixed `--create-debian-package`. Did it not work for you?

**Comment by hypersad** [comment]
@curiousercreative Oh, sorry, my mistake. I think you're fixed --install. Or it fixed in you PR too?

**Comment by curiousercreative** [comment]
@hypersad I was only able to fix package creation. The install flag still fails during build.

**Comment by djarami** [comment]
I tried it out and it looks like it built the deb pkg cleanly.  Here is the output:

```
Generating .deb file from /tmp/atom-1.15.0-armv7l
dpkg-deb: building package `atom' in `/tmp/atom-1.15.0-armv7l.deb'.
Copying generated package into "/home/pi/atom/out/atom-armhf.deb"
```

Now that I have this, how do I install it ?  I searched and I think I need to do this:
`dpkg -i atom-armhf.deb`

But after I did that, I got this:
```
pi@raspberrypi:~/atom/out $ sudo dpkg -i atom-armhf.deb
Selecting previously unselected package atom.
(Reading database ... 147054 files and directories currently installed.)
Preparing to unpack atom-armhf.deb ...
Unpacking atom (1.15.0) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on gvfs-bin; however:
  Package gvfs-bin is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Errors were encountered while processing:
 atom
```

**Comment by curiousercreative** [comment]
@djarami I had success installing it using gdebi, a GUI package installer. Give that a try and we'll see.

**Comment by djarami** [comment]
@curiousercreative ok, I'm trying it now before I start doing more builds.
For others that are new at this, here is what I had to do:
```
sudo apt-get -f install
sudo apt-get install gdebi
```
And then go to the UI and there was a gdebi icon on there, launch it, then open the atom-armf.deb file that is in the ./atom/out directory.

**Comment by djarami** [comment]
not sure if this belongs on this ticket or not, but when doing the clean build I got this at the end:

![image](https://cloud.githubusercontent.com/assets/4624027/25307318/f81a1e48-276c-11e7-899b-e578fe84664a.png)

Going to do re-clone and try again.

**Comment by hypersad** [comment]
@djarmi ENOMEM error means that your RAM is ended during installation. Just restart installation.

**Comment by djarami** [comment]
Ok, I did `node script/build  --install` and at the end I got the following.  Is there a sudo command that needs to be done somewhere ?
![image](https://cloud.githubusercontent.com/assets/4624027/25309039/1d13ee0e-2790-11e7-8b83-2c76d17faea8.png)

**Comment by djarami** [comment]
And sudo in front of the build --install command is no good either.

![image](https://cloud.githubusercontent.com/assets/4624027/25309053/68914886-2790-11e7-9f72-242f4ae95f4a.png)

**Comment by nonnymoose** [comment]
@curiousercreative If you want to install, you must build as root. `/usr/local` is, by default, owned by root.

**Comment by hypersad** [comment]
@nonnymoose Thanks for advice, but we need to find a way how to install it under user.

**Comment by nonnymoose** [comment]
@hypersad I understand, but keep in mind that Atom is *supposed* to install
under the system directory. Installing under user is uncommon, tricky, and
unstandardized in Linux.

**Comment by curiousercreative** [comment]
@nonnymoose @hypersad I think the goal for us is to have it work the same as it would on other architectures. So if a linux install on x86 architecture requires `sudo node script/build --install`, then that should be our target as well.

**Comment by curiousercreative** [comment]
I haven't tested this lately, can anyone confirm @djarami failing results for `sudo node script/build --install`? @nonnymoose. Has anyone tried this same command for Atom on Linux x86 and can confirm it succeeds?

**Comment by nonnymoose** [comment]
@winston I am unsure, but I know that @djarami 's failure was specifically
related to lack of root permissions.

**Comment by curiousercreative** [comment]
@nonnymoose he tried with `sudo` prepended and received a different failure: https://github.com/hypersad/atom/issues/5#issuecomment-296407834

**Comment by nonnymoose** [comment]
@djarami What if you su to root and then build instead?

**Comment by hypersad** [comment]
I can confirm thath build fails on start under sudo. Probably, it is because the node version is incorrect under sudo.

I will fix my tablet and attach some proofs :^)

**Comment by curiousercreative** [comment]
@hypersad @djarami I was able to run the install successfully using @nonnymoose suggestion of elevating access prior to usage via `su`. Try to reproduce with the following:
```
su
node script/build --install
```

**Comment by nonnymoose** [comment]
Okay, so that's a nodejs feature that automatically puts it in "strict"
mode if it's run with sudo. There should be a nodejs option to disable it.
Hang on, I'll read the manpage.

**Comment by nonnymoose** [comment]
@curiousercreative Okay, try `sudo node --no_use_strict script/build --install`.
Note: this option is not documented. I found it by brute-forcing possible options, so I hope it does what it should.

**Comment by djarami** [comment]
sudo produces an error,
without sudo it tries to build, but then errors out as before
![screen shot 2017-04-26 at 10 15 27 pm](https://cloud.githubusercontent.com/assets/4624027/25465044/e7b50b62-2acd-11e7-8287-77e9930970e8.jpg)

Doing a `su` and then produces errors as well:
![screen shot 2017-04-26 at 10 16 06 pm](https://cloud.githubusercontent.com/assets/4624027/25465061/105e9826-2ace-11e7-99ec-0e72d7854968.jpg)

**Comment by hypersad** [comment]
what about `node --version` under su?

**Comment by djarami** [comment]
It says:
root@raspberrypi:/home/pi# node --version
v0.10.29

So, does that mean I need to do the prep stuff under root ?

In the end, I don't know if this will even do what we need.  I think we need to work the ability to install the debian package from the command line.

**Comment by nonnymoose** [comment]
@David Install the package from the command line with `sudo dpkg -i
$PACKAGE_NAME`, replacing `$PACKAGE_NAME` with the filename of the package.

**Comment by djarami** [comment]
I think I tried that before and it had some package dependency issues.    I will try it again and report back.

**Comment by curiousercreative** [comment]
I was just able to build, install and create a debian package with the following:
```
su
node script/build --create-debian-package --install
```
Everything went smoothly for me. FWIW, under the superuser, `node --version` returns the same `v6.10.2` as under my default user. Closing this issue but don't let that keep discussion from continuing.

**Comment by djarami** [comment]
Ok, looks like I have an installed debian package from the command line.

![image](https://cloud.githubusercontent.com/assets/4624027/25604682/588ed288-2ed3-11e7-9057-145605cd1038.png)

Installed, on the menu and launched:
![image](https://cloud.githubusercontent.com/assets/4624027/25604699/777542e0-2ed3-11e7-9daa-63f58a436e19.png)

@hypersad  I think we just need to document these last steps in the readme.

I can't speak for the --install working on Pi, that might require updating node under root and testing that.

very cool.
